name: Format Check

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "format"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out this repository so this job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Library for format check
        run: |
          pip install -U --upgrade pip
          pip install -q yapf flake8 isort pyright
          
      # Run the flake8 format test
      - name: Flake8
        run: flake8 .

      # Run the isort format test
      - name: Isort
        run: isort --check-only .
